### ISSUE TITLE
File Rotation Error - Monolog writing to the old file even after the max file size is reached

### ISSUE THREAD

**Issue by slupud** [sgoettsch/monolog-rotating-file-handler#1]
Hi Team,

I am using monolog for my latest PHP project and wanted to have a rotating file handler based on max file size and I came across your package and it was very valuable. I tested your code but I found a small error in the log-rotation when the max size is reached. The issue was when the PHP script was running and producing logs, the full PHP script output (until the script is finished) was still written to the old file even its size has gone past the max-size. However, for each successive PHP script runs, the rotations worked in the beginning and a new file was created and the outputs were each written to the same old file in each case. This implied the current file size check was not working before each record was written. I added two lines as follows (commented with "//I added this") into "src/Handler/monologRotatingFileHandler.php" in the "write" method as follows and the problem was ok.

protected function write(array $record)
    {
        clearstatcache(true, $this->filename); 	//I added this
        
    	if(file_exists($this->filename)) {
			$fileSize = filesize($this->filename);
			if($fileSize >= $this->maxFileSize) {
				$this->mustRotate = true;
				$this->close(); 				//I added this
			}
		}
        parent::write($record);
    }

Before each record is written, PHP should clear the stat cache with "clearstatcache()" when calculating the new file size, otherwise, the calculated file size at the beginning of the script will cache throughout the execution of the PHP script and files will never be rotated. I got this hint after analyzing log4php code for its "rollingFileAppender". Also "$this->close()" has to be included (which will rotate/archive the file and create a new one) before "parent::write($record)".

If you can verify this and update your code as above or someway better than this that you can think of, that will be great for others who might face the same issue when using this package.

Cheers!

**Comment by sgoettsch** [comment]
Thank you for the feedback. I had a look at the bug and your suggested fix worked fine so i added it. 👍

**Comment by slupud** [comment]
That is good to know.

Cheers,
