### ISSUE TITLE
Support for monolog@2 ?

### ISSUE THREAD

**Issue by c01nd01r** [sgoettsch/monolog-rotating-file-handler#2]
Hi!
I trying install `monolog-rotating-file-handler`, but composer install `monolog` v1.
Any plans for support `monolog` v2 ?

**Comment by sgoettsch** [comment]
Yes, it is on my todo. Just need some time to test it

**Comment by sgoettsch** [comment]
Version 2.0.0 should now support monolog version 2 :)

**Comment by c01nd01r** [comment]
Thank you!
